### ISSUE TITLE
[Feature suggestion] Color by crature type

### ISSUE THREAD

**Issue by lucaspicerni** [shemetz/tokenmagic-automatic-wounds#2]
Hi! I'd like to suggest that the module choose the default blood color for a creature based on its type (like Aberrations in D&D), similar to what [Splatter](https://github.com/theripper93/Splatter) does. Or put a color picker in the token configuration menu, but not having to configure each creature manually would be great! Thank you for the work!

**Comment by CaosFR** [comment]
+10000 :) It will be great ! 
@shemetz Do you think you can add this feature ?

**Comment by shemetz** [comment]
I don't think I will, because:
- there are lots of creature types and maintaining the list will require a lot of effort - plus, a lot of them are really inconsistent within a type.  Even with undead - some want dark red blood, some blue blood, some black blood, some no blood at all.
- it will require even more system-dependent behavior, which I prefer to avoid as it makes maintenance harder

**Comment by CaosFR** [comment]
@shemetz I dont understand, I had in devellopement long time ago :)
Maybe you can be insperied by the work of theRipper93, it's module work for DnD5e and it's custom by users (so you dont have maintaining the list.

**Comment by lucaspicerni** [comment]
I believe this issue can be closed. Thanks for the improvement!
